### PR TITLE
Adding pinned versions documentation

### PR DESCRIPTION
**Pull request by asewnath**
## Description

Adding documentation for features that were added in PR #38 and #46.

### CODE REVIEW

**Comment by metdyn** [comment]
I am thinking that to make jedi_bundle self contained, it may be more smoother to rename 
`jedi_bundle_update_hash 2024-05-14` 
to 
`jedi_bundle --update_hash 2024-05-14`
or 
`jedi-bundle -hash 2024-05-14`

**Comment by asewnath** [comment]
> I am thinking that to make jedi_bundle self contained, it may be more smoother to rename `jedi_bundle_update_hash 2024-05-14` to `jedi_bundle --update_hash 2024-05-14` or `jedi-bundle -hash 2024-05-14`

Hi @metdyn, thanks for the comment. I chose to create a new command instead of another option to `jedi_bundle` because `jedi_bundle_update_hash` is meant to be a standalone tool. The intent is to give Swell managers the ability to easily retrieve and test all hashes before updating the `pinned_versions.yaml` file in the `jedi_bundle` repository and before updating the `jedi_bundle` build in `advda`. ( I don't believe most Swell users are expected to build `jedi_bundle` with different hashes themselves. They would use the existing `jedi_bundle` build in `advda` with the hashes Swell managers vet. This is currently the default behavior when running Swell experiments.)

If `jedi_bundle_update_hash` is changed to be an option, like `jedi_bundle --update_hash %Y-%m-%d`, I can change the code in the `jedi_bundle` bin to perform only the standalone script if that option is provided. However, given that this is meant to be a standalone tool, I believe that this unnecessarily adds logic to the already complex `jedi_bundle` executable. It also changes the executable's expected behavior, which is to create a `build.yaml` file if only the executable is called.

I could remove the assumption of a standalone tool by combining linking the `pinned_versions.yaml` file (`jedi_bundle -pv`) with the other flag to update hashes (or perhaps `jedi_bundle -pv %Y-%m-%d` would tell the program to add pinned hashes to the `build.yaml` but with hashes from a given date). But, I don't like the idea of combining all these features together just yet.

Given my rationale, please let me know what you think.

**Comment by metdyn** [comment]
Hi @asewnath,  thanks for your reply.
I am looking at nomenclature,  for example, git does not have git_pull, git_update, git_push etc.  On the other hand, if the software is not widely and frequently used, the function `jedi_bundle_update_hash` serves its purpose well. I have no other complaints.

**Comment by asewnath** [comment]
> Hi @asewnath, thanks for your reply. I am looking at nomenclature, for example, git does not have git_pull, git_update, git_push etc. On the other hand, if the software is not widely and frequently used, the function `jedi_bundle_update_hash` serves its purpose well. I have no other complaints.

Yes, that make sense and is a very good point. If the `jedi_bundle` command was a more general interface and not so tightly coupled with the creation and execution of `build.yaml`, it would make sense to add another keyword like `update_hash` which would perform the standalone script.

**Review by Dooruk — APPROVED** [review]
Thanks @asewnath, I added an example showing how `build.yaml` would look like. If you agree with that then that it's good to merge.

**Pull request merged**
