### PR TITLE
Spack-Stack 1.7.0 and Discover SLES15 Modules

### LINKED ISSUE #31: Add Discover SCU17 as a new platform
Spack-stack modules are available on Milan nodes, thanks to Dom and @mathomp4!

During transition, we need to have two platforms to use on Discover: `nccs_discover` and `nccs_discover_sles15`. As old SCU's get decommissioned we will then permanently switch to the `SLES15` one.

One major change is that we won't have a `miniconda` as Dom mentioned here:

https://github.com/JCSDA/spack-stack/issues/1011

### PR DESCRIPTION
**Pull request by Dooruk**
Including SLES15 platform and updating to spack-stack 1.7.0 modules.

Also changes the `gsibec` version

### CODE REVIEW

**Comment by gmao-jjin3** [comment]
@Dooruk  I cannot checkout your branch "feature/discover_sles15". Strange.

**Comment by gmao-jjin3** [comment]
> @Dooruk I cannot checkout your branch "feature/discover_sles15". Strange.

My bad. I didn't see that it was in "jedi-bundle".

**Review by danholdaway — APPROVED** [review]
Looks reasonable. Apologies if I broke the platform lookup thing for Disco.

**Comment by Dooruk** [comment]
> Looks reasonable. Apologies if I broke the platform lookup thing for Disco.

It was failing while discerning between the two Discover OS.

JEDI builds with the SLES12 Intel modules but `pip install` is giving `Illegal instruction` error.  I will ask Dom, I didn't get this error with SLES15 previously.

@mathomp4 could this be because we are trying to implement a unified spack environment on two different OS's?

**Comment by mathomp4** [comment]
Illegal instruction? Hmm. Well, you can get that if something compiled in a flag not supported on a chipset (say an Intel-only instruction that AMD chips have).

But often that's just a catch all for "things crashed".

Can you reproduce the crash on the commandline?

**Comment by Dooruk** [comment]
> Illegal instruction? Hmm. Well, you can get that if something compiled in a flag not supported on a chipset (say an Intel-only instruction that AMD chips have).


Dom switched the intel compiler to 2021.6.0 and now all is good. I need to make the necessary updates now...

Potential explanation by Dom:

>It is a combination of switching from zlib to zlib-ng AND using intel@2021.50 AND being on a particular system. We are only seeing this on Discover SLES12 and S4, and the problems go away when using an older 2021.3.0, 2021.4.0 or newer 2021.6.0+ version of the compiler. On other systems that use 2021.5.0 (e.g. the navy nautilus machine, which is penguin linux), we don’t see the issue.

Bonus:
Screenshot 2024-04-04 at 10 16 49 AM

**Pull request merged**
